### ISSUE TITLE
Issue 3: Make window/buttons constants

### ISSUE THREAD

**Issue by byrat** [byrat/Comp-55-Res#3]
If we were to change the window of the game to a constant and position entities in the game around the constant plus an amount of offset. We could get around having to change the whole program something needed to be added because the main window would move,

This change would be applied to the files that have to do with the display of the game. Mainly GraphicsGame.java and MenuPane.java

**Comment by onzfonz** [comment]
You will do this one, but will have the extra step of having those constants be in a file that can be modified by anyone so that by using some of the information in the file, you can then decide where something will be placed in the game.
Let me know if you have any questions about it!
